"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _courses_list from './courses-list.bones.json'

registerBones({
  "courses-list": _courses_list,
})
